### ISSUE TITLE
error when run 'yarn server'

### ISSUE THREAD

**Issue by Rimay** [microsoft/0xDeCA10B#90]
when I try to start the server from one terminal via 
`yarn server`
the following error occured:

```
root@4b935555249c:~/workspace/demo# yarn server
yarn run v1.22.0
$ nodemon server.js --ignore client/
[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
[nodemon] Internal watch failed: ENOSPC: System limit for number of file watchers reached, watch '/root/workspace/demo/blockchain_db/!trie_db!0x98bc7528aec5dba65ab2272c2844b472118d4e17cce298ee58a3a2848d407c32'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Does anyone know where went wrong?

**Comment by juharris** [comment]
Thanks for trying out the code!
Did you close the issue because you found a solution? If so can you share it?

It looks like you're starting the code from a Docker container. The part with: `Internal watch failed: ENOSPC: System limit for number of file watchers reached, watch '/root/workspace/demo/blockchain_db/!trie_db!0x98bc7528aec5dba65ab2272c2844b472118d4e17cce298ee58a3a2848d407c32'` is the clue we need. I can probably think of a few solutions if you still need help.
